"""Paraphrased variants of the 33 known Stage1 sentences (see test_data.py).

Each original sentence gets 2 reworded versions that preserve the same meaning
(same target_type/landmark/relation/situation), so the labels are INHERITED from
the original -- no new manual labeling needed. This exists to get a larger,
statistically steadier test set without the cost of hand-labeling hundreds of
new sentences from scratch.

relation for person-target entries (2026-08-15): extracted the same way as for
objects (on/near/beside), NOT forced to null -- see nlu/README.md for why. The 3
entries whose landmark is not actually named in the sentence text (hydrant/bicycle
cases inherited from the starter kit answer table) keep relation=null since no relation can
be read off the text either way. (2026-08-20: relation/landmark carry 0% scoring
weight for person-type problems in the real rubric -- kept anyway as our best
textual read, not scored either way.)

NOTE (2026-08-20): person entries' target_type/situation resynced from test_data.py
after cross-checking against real platform scoring data -- target_type is pose-qualified
(person_sitting/person_bending/...), never plain "person". See test_data.py's 2026-08-20
note for the full explanation.

Caveat: these are still built around the same 33 landmarks/objects, so they do
NOT test vocabulary generalization the way held_out_sentences.py does. Use both:
  - paraphrases.py  -> "does wording/phrasing variation trip up the parser?"
  - held_out_sentences.py -> "does the parser generalize to unseen words?"
"""

PARAPHRASE_EXAMPLES = [{'landmark': 'picnic_table',
  'relation': 'on',
  'sentence': "There's a mug on the picnic table, can you go find it?",
  'situation': None,
  'target_type': 'mug'},
 {'landmark': 'picnic_table',
  'relation': 'on',
  'sentence': 'I left my mug sitting on the picnic table earlier.',
  'situation': None,
  'target_type': 'mug'},
 {'landmark': 'bench',
  'relation': 'on',
  'sentence': 'Locate the tumbler resting on top of the bench.',
  'situation': None,
  'target_type': 'tumbler'},
 {'landmark': 'bench',
  'relation': 'on',
  'sentence': 'My tumbler is on the bench -- please retrieve it.',
  'situation': None,
  'target_type': 'tumbler'},
 {'landmark': 'hydrant',
  'relation': 'near',
  'sentence': "There's a tumbler close to the fire hydrant out in the parking lot.",
  'situation': None,
  'target_type': 'tumbler'},
 {'landmark': 'hydrant',
  'relation': 'near',
  'sentence': 'I left my tumbler by the hydrant in the parking lot somewhere.',
  'situation': None,
  'target_type': 'tumbler'},
 {'landmark': 'picnic_table',
  'relation': 'beside',
  'sentence': 'Locate the sunblock sitting next to the picnic table.',
  'situation': None,
  'target_type': 'sunblock'},
 {'landmark': 'picnic_table',
  'relation': 'beside',
  'sentence': 'My sunblock ended up right beside the picnic table.',
  'situation': None,
  'target_type': 'sunblock'},
 {'landmark': 'vending_machine',
  'relation': 'beside',
  'sentence': "There's an umbrella propped up next to the vending machine.",
  'situation': None,
  'target_type': 'umbrella'},
 {'landmark': 'vending_machine',
  'relation': 'beside',
  'sentence': 'I left my umbrella by the vending machine, could you grab it?',
  'situation': None,
  'target_type': 'umbrella'},
 {'landmark': 'trash_can',
  'relation': 'near',
  'sentence': "Locate the umbrella that's close to the trash can.",
  'situation': None,
  'target_type': 'umbrella'},
 {'landmark': 'trash_can',
  'relation': 'near',
  'sentence': 'My umbrella somehow ended up near the trash can.',
  'situation': None,
  'target_type': 'umbrella'},
 {'landmark': 'picnic_table',
  'relation': 'beside',
  'sentence': "There's a pencil case close to the picnic table, find it please.",
  'situation': None,
  'target_type': 'pencilcase'},
 {'landmark': 'picnic_table',
  'relation': 'beside',
  'sentence': 'I think I left my pencil case somewhere beside the picnic table.',
  'situation': None,
  'target_type': 'pencilcase'},
 {'landmark': 'police_car',
  'relation': 'beside',
  'sentence': "There's an umbrella that fell in an empty parking spot, go find it.",
  'situation': None,
  'target_type': 'umbrella'},
 {'landmark': 'police_car',
  'relation': 'beside',
  'sentence': 'I think I dropped my umbrella in an empty space in the parking lot.',
  'situation': None,
  'target_type': 'umbrella'},
 {'landmark': 'police_car',
  'relation': 'near',
  'sentence': "There's a tumbler that fell near an empty parking spot.",
  'situation': None,
  'target_type': 'tumbler'},
 {'landmark': 'police_car',
  'relation': 'near',
  'sentence': 'I dropped my tumbler somewhere in an empty parking space.',
  'situation': None,
  'target_type': 'tumbler'},
 {'landmark': 'taxi',
  'relation': 'near',
  'sentence': "There's a tumbler lying on the road close to the taxi.",
  'situation': None,
  'target_type': 'tumbler'},
 {'landmark': 'taxi',
  'relation': 'near',
  'sentence': 'My tumbler ended up on the road right by the taxi.',
  'situation': None,
  'target_type': 'tumbler'},
 {'landmark': 'taxi',
  'relation': 'near',
  'sentence': "There's an umbrella on the road close to the taxi.",
  'situation': None,
  'target_type': 'umbrella'},
 {'landmark': 'taxi',
  'relation': 'near',
  'sentence': 'I left my umbrella on the road near the taxi.',
  'situation': None,
  'target_type': 'umbrella'},
 {'landmark': 'vending_machine',
  'relation': 'beside',
  'sentence': 'I got a drink from the vending machine after my workout and forgot my umbrella '
              'leaning against it.',
  'situation': None,
  'target_type': 'umbrella'},
 {'landmark': 'vending_machine',
  'relation': 'beside',
  'sentence': 'Right after exercising I bought a drink from the machine, and my umbrella got left '
              'standing beside it.',
  'situation': None,
  'target_type': 'umbrella'},
 {'landmark': 'picnic_table',
  'relation': 'near',
  'sentence': 'I was jotting down notes at an outdoor table and forgot my pencil case there.',
  'situation': None,
  'target_type': 'pencilcase'},
 {'landmark': 'bench',
  'relation': 'beside',
  'sentence': 'While studying at a table outside, I left my pencil case behind.',
  'situation': None,
  'target_type': 'pencilcase'},
 {'landmark': 'picnic_table',
  'relation': 'on',
  'sentence': 'I was reading and having coffee at an outdoor table, and I think I left my mug '
              'there.',
  'situation': None,
  'target_type': 'mug'},
 {'landmark': 'picnic_table',
  'relation': 'on',
  'sentence': 'While reading outside with my coffee at a table, I forgot my mug.',
  'situation': None,
  'target_type': 'mug'},
 {'landmark': 'bench',
  'relation': 'beside',
  'sentence': "I was relaxing in the sun at the park and forgot the sunblock I'd been using.",
  'situation': None,
  'target_type': 'sunblock'},
 {'landmark': 'bench',
  'relation': 'beside',
  'sentence': 'While sunbathing at the park, I left behind the sunblock I had with me.',
  'situation': None,
  'target_type': 'sunblock'},
 {'landmark': 'bench',
  'relation': 'beside',
  'sentence': 'I bought a drink from the vending machine and left my umbrella leaning against it.',
  'situation': None,
  'target_type': 'umbrella'},
 {'landmark': 'bench',
  'relation': 'beside',
  'sentence': 'After getting a drink from the machine, my umbrella got left propped up beside it.',
  'situation': None,
  'target_type': 'umbrella'},
 {'landmark': 'trash_can',
  'relation': 'near',
  'sentence': 'I threw something away in the bin and forgot my umbrella leaning on the trash can.',
  'situation': None,
  'target_type': 'umbrella'},
 {'landmark': 'trash_can',
  'relation': 'near',
  'sentence': 'While tossing something into the trash can, I left my umbrella resting against it.',
  'situation': None,
  'target_type': 'umbrella'},
 {'landmark': 'police_car',
  'relation': 'near',
  'sentence': "I might've dropped my tumbler when I stepped out of my car in the parking lot.",
  'situation': None,
  'target_type': 'tumbler'},
 {'landmark': 'police_car',
  'relation': 'near',
  'sentence': 'Getting out of the car in the parking lot, I think my tumbler fell to the ground.',
  'situation': None,
  'target_type': 'tumbler'},
 {'landmark': 'bench',
  'relation': 'near',
  'sentence': "As I got out of the car, my umbrella fell into the empty spot beside it -- it's "
              'somewhere in the parking lot.',
  'situation': None,
  'target_type': 'umbrella'},
 {'landmark': 'bench',
  'relation': 'near',
  'sentence': 'I dropped my umbrella in an empty parking space right next to my car.',
  'situation': None,
  'target_type': 'umbrella'},
 {'landmark': 'trash_can',
  'relation': 'on',
  'sentence': "There's someone sitting on top of a trash can in the parking lot -- check on them.",
  'situation': 'abnormal',
  'target_type': 'person_sitting'},
 {'landmark': 'trash_can',
  'relation': 'on',
  'sentence': 'Someone climbed onto a trash can in the parking lot and is sitting there.',
  'situation': 'abnormal',
  'target_type': 'person_sitting'},
 {'landmark': 'vending_machine',
  'relation': 'on',
  'sentence': "There's someone sitting on top of the vending machine, please check on them.",
  'situation': 'abnormal',
  'target_type': 'person_sitting'},
 {'landmark': 'vending_machine',
  'relation': 'on',
  'sentence': 'Someone is perched on top of the vending machine.',
  'situation': 'abnormal',
  'target_type': 'person_sitting'},
 {'landmark': 'bench',
  'relation': 'on',
  'sentence': "There's someone lying face-down on the bench close to the taxi.",
  'situation': 'abnormal',
  'target_type': 'person_bending'},
 {'landmark': 'bench',
  'relation': 'on',
  'sentence': 'Near the taxi, a person is lying face-down on a bench.',
  'situation': 'abnormal',
  'target_type': 'person_bending'},
 {'landmark': 'picnic_table',
  'relation': 'on',
  'sentence': "There's someone lying on top of the picnic table.",
  'situation': 'abnormal',
  'target_type': 'person_lying_down'},
 {'landmark': 'picnic_table',
  'relation': 'on',
  'sentence': 'Someone climbed up and is lying on the picnic table.',
  'situation': 'abnormal',
  'target_type': 'person_lying_down'},
 {'landmark': 'hydrant',
  'relation': None,
  'sentence': 'Someone has collapsed on the ground in the parking lot -- please check.',
  'situation': 'emergency',
  'target_type': 'person_lying_down'},
 {'landmark': 'hydrant',
  'relation': None,
  'sentence': "There's a person down on the parking lot floor, they seem to have collapsed.",
  'situation': 'emergency',
  'target_type': 'person_lying_down'},
 {'landmark': 'bicycle',
  'relation': None,
  'sentence': 'Someone is lying face-down and not moving in the parking lot.',
  'situation': 'accident',
  'target_type': 'person_prone'},
 {'landmark': 'bicycle',
  'relation': None,
  'sentence': "There's a person motionless, face-down, somewhere in the parking lot.",
  'situation': 'accident',
  'target_type': 'person_prone'},
 {'landmark': 'bicycle',
  'relation': 'near',
  'sentence': "Someone has fallen next to a bicycle that's tipped over.",
  'situation': 'emergency',
  'target_type': 'person_bending'},
 {'landmark': 'bicycle',
  'relation': 'near',
  'sentence': "There's a person down on the ground beside a knocked-over bike.",
  'situation': 'emergency',
  'target_type': 'person_bending'},
 {'landmark': 'trash_can',
  'relation': 'near',
  'sentence': 'Someone is bent over and not moving near the trash can in the park rest area.',
  'situation': 'emergency',
  'target_type': 'person_bending'},
 {'landmark': 'trash_can',
  'relation': 'near',
  'sentence': "In the park rest area, there's a person hunched over and still, close to the trash "
              'can.',
  'situation': 'emergency',
  'target_type': 'person_bending'},
 {'landmark': 'trash_can',
  'relation': 'near',
  'sentence': 'A bunch of people are hanging out in the park, but the one near the trash can, bent '
              'over and completely still, needs actual help.',
  'situation': 'emergency',
  'target_type': 'person_bending'},
 {'landmark': 'trash_can',
  'relation': 'near',
  'sentence': "Everyone's relaxing at the park except one person by the trash can who's bent over "
              'and not moving -- they need assistance.',
  'situation': 'emergency',
  'target_type': 'person_bending'},
 {'landmark': 'bicycle',
  'relation': 'near',
  'sentence': "There's someone down next to a bike in the parking lot, looks like an accident "
              'happened.',
  'situation': 'accident',
  'target_type': 'person_prone'},
 {'landmark': 'bicycle',
  'relation': 'near',
  'sentence': 'A person is on the ground beside a bicycle in the parking lot -- seems like they '
              'were in an accident.',
  'situation': 'accident',
  'target_type': 'person_prone'},
 {'landmark': 'vending_machine',
  'relation': 'on',
  'sentence': 'Someone climbed up onto the drink machine, which is definitely not normal.',
  'situation': 'abnormal',
  'target_type': 'person_sitting'},
 {'landmark': 'vending_machine',
  'relation': 'on',
  'sentence': "There's a person who somehow got on top of the vending machine.",
  'situation': 'abnormal',
  'target_type': 'person_sitting'},
 {'landmark': 'trash_can',
  'relation': 'on',
  'sentence': 'Someone climbed up onto a trash can in the parking lot and is now sitting there.',
  'situation': 'abnormal',
  'target_type': 'person_sitting'},
 {'landmark': 'trash_can',
  'relation': 'on',
  'sentence': "There's a person perched on top of a trash can out in the parking lot.",
  'situation': 'abnormal',
  'target_type': 'person_sitting'},
 {'landmark': 'bench',
  'relation': 'on',
  'sentence': "There's someone lying on top of a bench close to the taxi.",
  'situation': 'abnormal',
  'target_type': 'person_bending'},
 {'landmark': 'bench',
  'relation': 'on',
  'sentence': 'By the taxi, a person is stretched out on top of a bench.',
  'situation': 'abnormal',
  'target_type': 'person_bending'},
 {'landmark': 'bicycle',
  'relation': None,
  'sentence': 'There are several people in the parking lot, but one is face-down and not moving at '
              "all -- that's the urgent one.",
  'situation': 'accident',
  'target_type': 'person_prone'},
 {'landmark': 'bicycle',
  'relation': None,
  'sentence': 'Among the people in the parking lot, one is lying completely still, face-down -- '
              'find that person first.',
  'situation': 'accident',
  'target_type': 'person_prone'}]
